export const dummy = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/dueiWzWc81UAgnbDAyH4Gjqnh4n.jpg',
      genre_ids: [18, 878],
      id: 614911,
      original_language: 'en',
      original_title: 'The Midnight Sky',
      overview:
        'A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe. Get more than they bargained for as they lean into their newfound powers.',
      popularity: 1763.152,
      poster_path: '/51JxCk77ZCqLzbLkrDl9Qho6KUh.jpg',
      release_date: '2020-12-10',
      title: 'The Midnight Sky',
      video: false,
      vote_average: 6,
      vote_count: 614,
    },

    {
      adult: false,
      backdrop_path: '/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg',
      genre_ids: [12, 14, 28],
      id: 120,
      original_language: 'en',
      original_title: 'The Lord of the Rings: The Fellowship of the Ring',
      overview:
        'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.',
      popularity: 101.633,
      poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
      release_date: '2001-12-18',
      title: 'The Lord of the Rings: The Fellowship of the Ring',
      video: false,
      vote_average: 8.3,
      vote_count: 18296,
    },
    {
      adult: false,
      backdrop_path: '/lIE7kfdLBRd0KENNtOaIqPPWNqh.jpg',
      genre_ids: [27, 18, 14],
      id: 590995,
      original_language: 'en',
      original_title: 'The Craft: Legacy',
      overview:
        'An eclectic foursome of aspiring teenage witches get more than they bargained for as they lean into their newfound powers.',
      popularity: 540.862,
      poster_path: '/lhMIra0pqWNuD6CIXoTmGwZ0EBS.jpg',
      release_date: '2020-10-28',
      title: 'The Craft: Legacy',
      video: false,
      vote_average: 6,
      vote_count: 212,
    },
    {
      adult: false,
      backdrop_path: '/cjaOSjsjV6cl3uXdJqimktT880L.jpg',
      genre_ids: [12, 14, 10751, 16],
      id: 529203,
      original_language: 'en',
      original_title: 'The Croods: A New Age',
      overview:
        "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
      popularity: 1982.471,
      poster_path: '/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg',
      release_date: '2020-11-25',
      title: 'The Croods: A New Age',
      video: false,
      vote_average: 7.8,
      vote_count: 848,
    },
    {
      adult: false,
      backdrop_path: '/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg',
      genre_ids: [14, 10751, 12, 35, 27],
      id: 531219,
      original_language: 'en',
      original_title: "Roald Dahl's The Witches",
      overview:
        "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
      popularity: 496.953,
      poster_path: '/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg',
      release_date: '2020-10-26',
      title: "Roald Dahl's The Witches",
      video: false,
      vote_average: 6.8,
      vote_count: 1033,
    },
    {
      adult: false,
      backdrop_path: '/2AFZyra0Ddwl2oBDhClvD1qSIL6.jpg',
      genre_ids: [28, 27, 878],
      id: 340102,
      original_language: 'en',
      original_title: 'The New Mutants',
      overview:
        'Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.',
      popularity: 409.414,
      poster_path: '/xrI4EnZWftpo1B7tTvlMUXVOikd.jpg',
      release_date: '2020-08-26',
      title: 'The New Mutants',
      video: false,
      vote_average: 6.4,
      vote_count: 1244,
    },
    {
      adult: false,
      backdrop_path: '/9pHxv7TX0jOKNgnGMDP6RJ2m1GL.jpg',
      genre_ids: [28, 53],
      id: 737568,
      original_language: 'en',
      original_title: 'The Doorman',
      overview:
        "A former Marine turned doorman at a luxury New York City high-rise must outsmart and battle a group of art thieves and their ruthless leader — while struggling to protect her sister's family. As the thieves become increasingly desperate and violent, the doorman calls upon her deadly fighting skills to end the showdown.",
      popularity: 213.168,
      poster_path: '/pklyUbh4k1DbHdnsOMASyw7C6NH.jpg',
      release_date: '2020-10-01',
      title: 'The Doorman',
      video: false,
      vote_average: 6.1,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: '/t4V82jen6LKBjs8WMuMpGxbtFgJ.jpg',
      genre_ids: [35],
      id: 633908,
      original_language: 'en',
      original_title: 'The Stand In',
      overview:
        'When ordered to serve a year in rehab, actress Candy hires her on-set stand-in to take her place. The unassuming woman flips the script and steals her identity, career and boyfriend in this hilarious comedy about trading places.',
      popularity: 263.684,
      poster_path: '/twQeFldoNaDnMYXmZNXpm3NHlhP.jpg',
      release_date: '2020-12-03',
      title: 'The Stand In',
      video: false,
      vote_average: 5.5,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: '/wCkGiBE4swpWwJ0C8zJLr0WNH04.jpg',
      genre_ids: [12, 28, 53],
      id: 52451,
      original_language: 'en',
      original_title: 'The Three Musketeers',
      overview:
        "The hot-headed young D'Artagnan along with three former legendary but now down on their luck Musketeers must unite and defeat a beautiful double agent and her villainous employer from seizing the French throne and engulfing Europe in war.",
      popularity: 397.785,
      poster_path: '/w2LbQ8FvZiQpWvZyHljaOeiNknK.jpg',
      release_date: '2011-08-31',
      title: 'The Three Musketeers',
      video: false,
      vote_average: 5.8,
      vote_count: 1982,
    },
    {
      adult: false,
      backdrop_path: '/g0Aow7CTux0G4UApKrrnK6KbtHg.jpg',
      genre_ids: [14, 28, 35, 878, 10751],
      id: 11244,
      original_language: 'en',
      original_title: 'The Meteor Man',
      overview:
        "One night Jefferson Reed gets hit in the chest by a souped-up chunk of meteor. So he can fly, but he's scared of heights. He can master the information in any book ... for about thirty seconds. Now his friends and family want him to protect their community from the dreaded Golden Lords.",
      popularity: 338.786,
      poster_path: '/d30mZVOrY8n5KCvwaPkiQEFv1tc.jpg',
      release_date: '1993-08-06',
      title: 'The Meteor Man',
      video: false,
      vote_average: 5.2,
      vote_count: 86,
    },
    {
      adult: false,
      backdrop_path: '/juc9wt7Eh2IarLL5S1yQ1a21O1A.jpg',
      genre_ids: [16, 10751, 35, 14],
      id: 360920,
      original_language: 'en',
      original_title: 'The Grinch',
      overview:
        'The Grinch hatches a scheme to ruin Christmas when the residents of Whoville plan their annual holiday celebration.',
      popularity: 169.997,
      poster_path: '/stAu0oF6dYDhV5ssbmFUYkQPtCP.jpg',
      release_date: '2018-11-08',
      title: 'The Grinch',
      video: false,
      vote_average: 6.8,
      vote_count: 2403,
    },
    {
      adult: false,
      backdrop_path: '/7JCYI5Xrgt21fEQXIZ2ZFCRhyqK.jpg',
      genre_ids: [28, 12, 16, 35, 10751, 14],
      id: 49519,
      original_language: 'en',
      original_title: 'The Croods',
      overview:
        'The prehistoric Croods family live in a particularly dangerous moment in time. Patriarch Grug, his mate Ugga, teenage daughter Eep, son Thunk, and feisty Gran gather food by day and huddle together in a cave at night. When a more evolved caveman named Guy arrives on the scene, Grug is distrustful, but it soon becomes apparent that Guy is correct about the impending destruction of their world.',
      popularity: 176.868,
      poster_path: '/27zvjVOtOi5ped1HSlJKNsKXkFH.jpg',
      release_date: '2013-03-20',
      title: 'The Croods',
      video: false,
      vote_average: 6.9,
      vote_count: 5084,
    },
    {
      adult: false,
      backdrop_path: '/zKv7KF0pH9ASv2uGgTvTylMlxQn.jpg',
      genre_ids: [37],
      id: 729648,
      original_language: 'en',
      original_title: 'The Dalton Gang',
      overview:
        "When their brother Frank is killed by an outlaw, brothers Bob Dalton, Emmett Dalton and Gray Dalton join their local sheriff's department. When they are cheated by the law, they turn to crime, robbing trains and anything else they can steal from over the course of two years in the early 1890's. Trying to out do Jesse James, they attempt to rob two banks at once in October of 1892, and things get ugly",
      popularity: 327.65,
      poster_path: '/6OeGqp18oZucUGziMIRNhLouZ75.jpg',
      release_date: '2020-11-02',
      title: 'The Dalton Gang',
      video: false,
      vote_average: 4.4,
      vote_count: 49,
    },
    {
      adult: false,
      backdrop_path: '/tJRbPH8Q0divR3UkdpVxmNcd1YE.jpg',
      genre_ids: [12, 16, 35, 10751],
      id: 9948,
      original_language: 'en',
      original_title: 'The Fox and the Hound 2',
      overview:
        'Best friends Tod, a fox kit, and Copper, a hound puppy, visit a country fair when they see a band of dogs called "The Singin\' Strays". The band has five members: Dixie, Cash, Granny Rose, and twin brothers Waylon and Floyd. It is important that they perform well because a talent scout is visiting.',
      popularity: 127.993,
      poster_path: '/mIhKia4eMOBCYgHSHLHXQ01oc2A.jpg',
      release_date: '2006-11-09',
      title: 'The Fox and the Hound 2',
      video: false,
      vote_average: 5.9,
      vote_count: 417,
    },
    {
      adult: false,
      backdrop_path: '/bVmSXNgH1gpHYTDyF9Q826YwJT5.jpg',
      genre_ids: [28, 12, 14],
      id: 122917,
      original_language: 'en',
      original_title: 'The Hobbit: The Battle of the Five Armies',
      overview:
        "Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.",
      popularity: 113.214,
      poster_path: '/xT98tLqatZPQApyRmlPL12LtiWp.jpg',
      release_date: '2014-12-10',
      title: 'The Hobbit: The Battle of the Five Armies',
      video: false,
      vote_average: 7.3,
      vote_count: 10507,
    },
    {
      adult: false,
      backdrop_path: '/htBUhLSS7FfHtydgYxUWjL3J1Q1.jpg',
      genre_ids: [16, 12, 10751, 14],
      id: 560050,
      original_language: 'en',
      original_title: 'Over the Moon',
      overview:
        'In this animated musical, a girl builds a rocket ship and blasts off, hoping to meet a mythical moon goddess.',
      popularity: 268.452,
      poster_path: '/lQfdytwN7eh0tXWjIiMceFdBBvD.jpg',
      release_date: '2020-10-16',
      title: 'Over the Moon',
      video: false,
      vote_average: 7.6,
      vote_count: 592,
    },
    {
      adult: false,
      backdrop_path: '/zLTfRrrVXNW3OWUk6U1eFZhB18m.jpg',
      genre_ids: [28, 35, 16],
      id: 347201,
      original_language: 'ja',
      original_title: 'BORUTO -NARUTO THE MOVIE-',
      overview:
        "Boruto is the son of the 7th Hokage Naruto who completely rejects his father. Behind this, he has feelings of wanting to surpass Naruto, who is respected as a hero. He ends up meeting his father's friend Sasuke, and requests to become... his apprentice!? The curtain on the story of the new generation written by Masashi Kishimoto rises!",
      popularity: 167.259,
      poster_path: '/1k6iwC4KaPvTBt1JuaqXy3noZRY.jpg',
      release_date: '2015-08-07',
      title: 'Boruto: Naruto the Movie',
      video: false,
      vote_average: 7.8,
      vote_count: 654,
    },
    {
      adult: false,
      backdrop_path: '/ovwN1JDPvllWZaH3xtKp7txRWDj.jpg',
      genre_ids: [27],
      id: 715658,
      original_language: 'en',
      original_title: 'The Scientist',
      overview:
        'An unconventional scientist, struggling to care for his terminally-ill wife, embarks on a journey to develop a cure for her. However, his methods of treatment and tampering with human DNA, could lead to the extinction of humanity.',
      popularity: 160.68,
      poster_path: '/hIkKM1nlzk8DThFT4vxgW1KoofL.jpg',
      release_date: '2020-09-21',
      title: 'The Scientist',
      video: false,
      vote_average: 6.3,
      vote_count: 64,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
